### ISSUE TITLE
Most sensors not working

### ISSUE THREAD

**Issue by camcs1** [YeonV/ledfxrm#16]
## Version of the custom_component

0.2.9
## Configuration

```yaml

host: 192.168.1.56
port: 8888
scan interval in seconds: 300

Create Entities for SubDevices: unchecked
Add Start/Stop-Server custom-endpoint: unchecked
Add Virtual-Lights (requires LedFx >0.9.2): unchecked 

```

## Environment Description 

LedFX hosted on Windows, with one device (WLED) added and 2 scenes defined. Home Assistant core 2021.7.1

## Describe the bug

All sensors show a value of 0 apart from server status which shows connected but doesn't change state when LedFX is closed. Scene selector on the light entity also shows all 0's 

## Debug log

```text

Error while setting up ledfxrm platform for light

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ledfxrm/light.py", line 51, in async_setup_entry
    for k in virtuals:
TypeError: 'NoneType' object is not iterable


```

## LedFX Config 

```json
{
    "audio": {
        "device_index": 0
    },
    "crossfade": 1.0,
    "custom_presets": {},
    "dev_mode": false,
    "devices": [
        {
            "config": {
                "center_offset": 0,
                "channel_count": 636,
                "channel_offset": 0,
                "e131_Packet_Priority": 100,
                "force_refresh": false,
                "icon_name": "SettingsInputComponent",
                "ip_address": "192.168.1.160",
                "max_brightness": 1,
                "name": "WLED",
                "pixel_count": 212,
                "preview_only": false,
                "refresh_rate": 60,
                "type": "e131",
                "universe": 1,
                "universe_end": 2,
                "universe_size": 510
            },
            "id": "wled",
            "type": "e131"
        }
    ],
    "fade": 1.0,
    "host": "192.168.1.56",
    "integrations": [],
    "max_workers": 10,
    "port": 8888,
    "presets": {
        "subbass": {
            "devices": {
                "wled1": {
                    "config": {
                        "blur": 1.0,
                        "brightness": 1.0,
                        "flip": false,
                        "frequency_range": "sub_bass",
                        "gradient_method": "bezier",
                        "gradient_name": "Spectral",
                        "gradient_roll": 1,
                        "mirror": true
                    },
                    "type": "beat(Reactive)"
                }
            },
            "name": "subbass"
        }
    },
    "scenes": {
        "bass": {
            "devices": {
                "wled": {
                    "config": {
                        "background_color": "black",
                        "blur": 2.3114887329706866,
                        "brightness": 1.0,
                        "flip": true,
                        "frequency_range": "Bass (60-250Hz)",
                        "gradient_name": "Viridis",
                        "gradient_repeat": 1,
                        "gradient_roll": 7,
                        "mirror": true
                    },
                    "type": "magnitude(Reactive)"
                }
            },
            "name": "Bass"
        },
        "orange": {
            "devices": {
                "wled": {
                    "config": {
                        "active": true,
                        "background_color": "black",
                        "blur": 3.0,
                        "brightness": 1.0,
                        "flip": false,
                        "gradient_name": "Rust",
                        "gradient_repeat": 1,
                        "gradient_roll": 0,
                        "mirror": false
                    },
                    "type": "wavelength(Reactive)"
                }
            },
            "name": "Orange"
        }
    },
    "virtuals": []
}
```

**Comment by axelcypher** [comment]
Same Error here :/
