### ISSUE TITLE
Error when adding devices

### ISSUE THREAD

**Issue by trancefam** [YeonV/ledfxrm#6]
## Version of the custom_component

0.2.5
## Configuration

```yaml

None

```

## Describe the bug

Hello, Thank you very much for the integration, it is exactly what I'm looking for! I am having an issue when trying to add devices. I receive the following error log. I am on the latest version of HA. The issue persists even after following the "messed up" guide in the wiki. 

## Debug log

```text
Error adding entities for domain light with platform ledfxrm
Error while setting up ledfxrm platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 427, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/ledfxrm/light.py", line 185, in icon
    if self.deviceconfig["icon_name"].startswith("mdi:"):
KeyError: 'icon_name'
```

**Comment by trancefam** [comment]
I've confirmed that v0.2.4 does not have this issue

**Comment by YeonV** [comment]
Will look into it today. Thx for testing. (also you need the LATEST dev-branch of ledfx)
@trancefam join our discord bro

**Comment by YeonV** [comment]
@trancefam  Could you try with v0.2.6?
